'use client'
import { FormEvent, useState } from 'react'

type Evidence = { category:string; claim:string; sourceUrl?:string; sourceName?:string; sourceType?:string; polarity:string; strength:number; excerpt?:string; publishedAt?:string }
type Dimension = { name:string; score:number; rationale:string; strengths:string[]; weaknesses:string[]; improvements:string[] }
type Improvement = { problem:string; change:string; whyItCouldHelp:string; evidence:Evidence[]; expectedImpact:{dimension:string;from:number;to:number;reason:string}[] }
type Result = { verdict:string; score:number; confidence:number; evidenceStatus:string; summary:string; dimensions:Dimension[]; strengths:string[]; weaknesses:string[]; improvements:Improvement[]; evidence:Evidence[]; nextSteps:string[]; message?:string }

export default function Home(){
 const [idea,setIdea]=useState(''); const [customer,setCustomer]=useState(''); const [location,setLocation]=useState(''); const [result,setResult]=useState<Result|null>(null); const [loading,setLoading]=useState(false); const [error,setError]=useState('')
 async function validate(e:FormEvent){e.preventDefault(); if(idea.trim().length<12||customer.trim().length<2)return; setLoading(true);setError('');setResult(null); try{const r=await fetch('/api/validate',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({idea,customer,location})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Validation failed');setResult(d)}catch(x){setError(x instanceof Error?x.message:'Something went wrong.')}finally{setLoading(false)}}
 return <main className="shell"><nav><div className="brand"><span className="brand-mark">V</span> VentureProof</div><span className="nav-pill">EVIDENCE-FIRST VALIDATION</span></nav>
 <section className="hero"><span className="eyebrow">✦ BUILD WITH EVIDENCE, NOT EGO</span><h1>Don't kill your dream.<br/><em>Make it stronger.</em></h1><p className="hero-copy">Stress-test an idea against market signals, then see what is strong, what is weak, what to change, and what evidence supports the change.</p></section>
 <section className="workspace"><form className="card intake" onSubmit={validate}><div className="card-head"><div><span className="step">01</span><h2>Describe the venture</h2></div><span className="live">● LIVE ENGINE</span></div><label>What are you building?<textarea value={idea} onChange={e=>setIdea(e.target.value)} placeholder="Describe the product, problem and how it works..." maxLength={2000}/></label><div className="two-col"><label>Target customer<input value={customer} onChange={e=>setCustomer(e.target.value)} placeholder="e.g. small retailers"/></label><label>Market / geography<input value={location} onChange={e=>setLocation(e.target.value)} placeholder="e.g. Kenya, East Africa"/></label></div><button className="primary" disabled={loading||idea.trim().length<12||customer.trim().length<2}>{loading?'Researching evidence…':'Validate & improve my idea →'}</button><p className="disclaimer">A low score is not a death sentence. We surface the assumptions that need work and show how a stronger version could perform. Evidence and confidence are always shown separately.</p></form>
 <section className="card results" aria-live="polite">{!result&&!loading&&!error&&<div className="empty"><div className="orb">✦</div><h2>Your evidence report appears here</h2><p>Submit an idea to generate strengths, weaknesses, proof, improvement paths and an evidence-backed before/after view.</p></div>}{loading&&<div className="empty"><div className="loader"/><h2>Researching the market</h2><p>Triangulating independent signals and preparing your improvement report.</p></div>}{error&&<div className="empty"><div className="error-icon">!</div><h2>We hit a snag</h2><p>{error}</p></div>}{result&&<Report result={result}/>}</section></section><footer><span>VENTUREPROOF</span><span>Evidence over enthusiasm.</span><span>Private MVP · 2026</span></footer></main>}

function Report({result}:{result:Result}){return <div className="report"><div className="report-top"><div><span className="step">02</span><h2>Your opportunity report</h2></div><span className={`decision ${result.verdict.toLowerCase()}`}>{result.verdict==='PAUSE'?'PAUSE & IMPROVE':result.verdict}</span></div><div className="score-row"><div><span className="score-label">OPPORTUNITY SCORE</span><strong>{result.score}</strong><span>/100</span></div><div className="summary"><b>{result.summary}</b><p>Confidence <strong>{result.confidence}%</strong> · {result.evidenceStatus}</p></div></div><div className="report-section"><div className="section-title"><span>03</span><h3>What is strong</h3></div><div className="chips">{result.strengths.length?result.strengths.map((x,i)=><div className="insight good" key={i}>✓ {x}</div>):<div className="insight">No strength is yet strongly evidenced.</div>}</div></div><div className="report-section"><div className="section-title"><span>04</span><h3>What is weak</h3></div><div className="chips">{result.weaknesses.length?result.weaknesses.map((x,i)=><div className="insight bad" key={i}>! {x}</div>):<div className="insight">No major weakness surfaced in the current evidence.</div>}</div></div><div className="report-section"><div className="section-title"><span>05</span><h3>Dimension scorecard</h3></div><div className="dimensions">{result.dimensions.map(d=><article className="dimension" key={d.name}><div className="dim-head"><span>{d.name}</span><b>{d.score}</b></div><div className="bar"><i style={{width:`${d.score}%`}}/></div><p>{d.rationale}</p>{d.improvements.map((x,i)=><small key={i}>→ {x}</small>)}</article>)}</div></div><div className="report-section improve"><div className="section-title"><span>06</span><h3>How to improve the idea</h3></div>{result.improvements.map((x,i)=><article className="improvement" key={i}><span className="number">0{i+1}</span><div><h4>{x.problem}</h4><p><b>Change:</b> {x.change}</p><p><b>Why this could help:</b> {x.whyItCouldHelp}</p><div className="impact"><b>Projected impact</b>{x.expectedImpact.map((e,j)=><span key={j}>{e.dimension}: {e.from} → <strong>{e.to}</strong> <em>{e.reason}</em></span>)}</div>{x.evidence.length>0&&<EvidenceList items={x.evidence}/>}</div></article>)}</div><div className="report-section"><div className="section-title"><span>07</span><h3>Proof & evidence</h3></div><EvidenceList items={result.evidence}/></div><div className="report-section next"><div className="section-title"><span>08</span><h3>Do this next</h3></div>{result.nextSteps.map((x,i)=><div className="next-item" key={i}><span>{String(i+1).padStart(2,'0')}</span>{x}</div>)}</div>{result.message&&<p className="disclaimer">{result.message}</p>}<button className="secondary" onClick={()=>window.scrollTo({top:0,behavior:'smooth'})}>Test another venture</button></div>}
function EvidenceList({items}:{items:Evidence[]}){return <div className="evidence-list">{items.length?items.map((e,i)=><div className="evidence" key={i}><div className="ev-meta"><span>{e.sourceType||'source'}</span><span>{e.polarity}</span><span>strength {e.strength}/100</span></div><p>{e.claim}</p>{e.sourceUrl?<a href={e.sourceUrl} target="_blank" rel="noreferrer">{e.sourceName||e.sourceUrl} ↗</a>:<small>Baseline — not external market proof</small>}</div>):<div className="evidence">No external evidence retrieved.</div>}</div>}
