export type Verdict='BUILD'|'PIVOT'|'PAUSE'|'INSUFFICIENT_EVIDENCE'
export type Polarity='positive'|'negative'|'neutral'|'mixed'
export type Evidence={category:string;lane?:string;claim:string;sourceUrl?:string;sourceName?:string;sourceType?:string;sourcePublisher?:string;polarity:Polarity;strength:number;excerpt?:string;publishedAt?:string;retrievedAt?:string;freshness?:'fresh'|'recent'|'stale'|'unknown';relevance?:number;supports?:string}
export type Dimension={name:string;score:number;rationale:string;strengths:string[];weaknesses:string[];improvements:string[]}
export type Improvement={problem:string;change:string;whyItCouldHelp:string;evidence:Evidence[];expectedImpact:{dimension:string;from:number;to:number;reason:string}[];validationTest:string}
export type Competitor={name:string;url:string;description:string;evidence:Evidence[];threat:'high'|'medium'|'low'}
export type Result={verdict:Verdict;score:number;confidence:number;evidenceStatus:string;summary:string;dimensions:Dimension[];strengths:string[];weaknesses:string[];improvements:Improvement[];evidence:Evidence[];competitors:Competitor[];nextSteps:string[];researchStats:{sources:number;independentSources:number;freshSources:number;supporting:number;contradicting:number;neutral:number;redditSignals:number;freelanceSignals:number;newsSignals:number;expertSignals:number;bookSignals:number};methodology:string}
const clamp=(n:number)=>Math.max(0,Math.min(100,Math.round(n)))
const freshness=(date?:string):Evidence['freshness']=>{if(!date)return'unknown';const age=(Date.now()-new Date(date).getTime())/86400000;return age<=30?'fresh':age<=180?'recent':age<=730?'stale':'stale'}
function actualRiskEvidence(e:Evidence){const t=`${e.sourceName||''} ${e.claim||''} ${e.excerpt||''}`.toLowerCase();return /tcp(a|f)|gdpr|pecr|can-spam|do[- ]not[- ]call|dnc|consent|call recording|data protection|privacy|security breach|spam|deliverability|compliance|regulation|telemarketing law|legal risk|fraud|operational capacity|list quality/.test(t)}
function categoryScore(items:Evidence[],category:string,base=45){const xs=items.filter(e=>e.category===category&&(category!=='risk'||actualRiskEvidence(e)));if(!xs.length)return base;const usable=xs.filter(e=>e.sourceUrl);if(!usable.length)return base;const weighted=usable.reduce((s,e)=>s+e.strength*(e.polarity==='positive'?1:e.polarity==='negative'?-1:0),0);return clamp(base+weighted/Math.max(1,usable.length)*0.55)}
function competitivePositionScore(e:Evidence[]){const xs=e.filter(x=>x.category==='competition'&&x.sourceUrl&&competitorRelevance(x));if(!xs.length)return 65;const domains=new Set(xs.map(x=>competitorHost(x.sourceUrl!))).size;const direct=xs.filter(x=>/appointment setting|cold calling|lead generation service|sales development|outbound sales|sdr agency|sales outsourcing/i.test(`${x.claim||''} ${x.excerpt||''}`)).length;const strong=xs.filter(x=>x.strength>=70).length;const pressure=Math.min(45,domains*3+direct*2+strong);return clamp(78-pressure)}
function competitorHost(url:string){try{return new URL(url).hostname.replace(/^www\./,'')}catch{return url}}
function competitorRelevance(x:Evidence){const t=`${x.sourceName||''} ${x.claim||''} ${x.excerpt||''}`.toLowerCase();const service=/lead generation|appointment setting|cold call|sales development|outbound|prospecting|sdr|sales outsourcing|pipeline/.test(t);const editorial=/(blog|guide|best |top |comparison|review|ranked|companies)/.test(t);return service&&!editorial}
function makeCompetitors(e:Evidence[]):Competitor[]{const groups=new Map<string,Evidence[]>();for(const x of e.filter(x=>x.category==='competition'&&x.sourceUrl&&competitorRelevance(x))){const key=competitorHost(x.sourceUrl!);if(!groups.has(key))groups.set(key,[]);groups.get(key)!.push(x)}return [...groups.entries()].slice(0,10).map(([host,ev])=>{const text=ev.map(x=>`${x.sourceName||''} ${x.claim||''} ${x.excerpt||''}`).join(' ').toLowerCase();const direct=/appointment setting|cold calling|lead generation service|sales development|outbound sales|sdr agency|sales outsourcing/.test(text);const threat:Competitor['threat']=direct&&ev.length>=2?'high':direct?'medium':'low';return{name:host,url:ev[0].sourceUrl!,description:ev[0].claim,evidence:ev.slice(0,4),threat}})}
export function scoreEvidence(evidence:Evidence[],idea='',customer=''):Result{
 const demand=categoryScore(evidence,'demand',45),problem=categoryScore(evidence,'problem',45),competition=competitivePositionScore(evidence),monetization=categoryScore(evidence,'monetization',45),acquisition=categoryScore(evidence,'acquisition',45),risk=categoryScore(evidence,'risk',65)
 const dimensions:Dimension[]=[
 {name:'Demand',score:demand,rationale:demand>=65?'Multiple market or customer-intent signals support demand.':'Demand needs stronger direct evidence from people actively seeking the solution.',strengths:demand>=65?['Market/customer-intent signals are visible.']:[],weaknesses:demand<65?['Demand is not yet strongly demonstrated.']:[],improvements:['Test the highest-intent segment with a concrete offer.']},
 {name:'Problem',score:problem,rationale:problem>=65?'Observed pain signals support a meaningful problem.':'Frequency, severity and current workaround need stronger evidence.',strengths:problem>=65?['Observed pain signals support the problem.']:[],weaknesses:problem<65?['Pain severity is not sufficiently established.']:[],improvements:['Collect evidence about recent behavior, cost and urgency.']},
 {name:'Competition',score:competition,rationale:competition>=65?'Competitive pressure appears manageable relative to the evidence retrieved.':competition>=45?'A meaningful competitive set exists; differentiation should be tested.':'Strong direct competition creates substantial differentiation pressure.',strengths:competition>=65?['No dense direct competitive set was established in the retrieved evidence.']:[],weaknesses:competition<55?['Direct or adjacent alternatives create meaningful differentiation pressure.']:[],improvements:['Define one underserved customer segment and measurable differentiation.']},
 {name:'Monetization',score:monetization,rationale:monetization>=65?'Pricing and payment signals support a plausible monetization path.':'Willingness to pay remains insufficiently demonstrated.',strengths:monetization>=65?['Comparable payment signals were found.']:[],weaknesses:monetization<65?['Pricing/WTP evidence is limited.']:[],improvements:['Test price and commitment before deep development.']},
 {name:'Acquisition',score:acquisition,rationale:acquisition>=65?'A plausible customer channel is visible.':'The route to the first customers remains uncertain.',strengths:acquisition>=65?['A reachable acquisition channel is visible.']:[],weaknesses:acquisition<65?['First-customer acquisition is not sufficiently evidenced.']:[],improvements:['Design a first-100-customer experiment around the strongest intent channel.']},
 {name:'Risk',score:risk,rationale:risk>=65?'No dominant structural risk signal was established.':'Material risks require mitigation and direct testing.',strengths:risk>=65?['No dominant structural risk signal found.']:[],weaknesses:risk<65?['Material risk signals need mitigation.']:[],improvements:['Turn the highest-impact risk into a validation experiment.']}]
 const score=clamp(dimensions.reduce((s,d)=>s+d.score,0)/6),independent=new Set(evidence.map(e=>e.sourceUrl).filter(Boolean)).size,fresh=evidence.filter(e=>e.freshness==='fresh'||e.freshness==='recent').length
 const confidence=clamp(18+Math.min(42,independent*4)+Math.min(20,evidence.length*1.2)+Math.min(20,fresh*2))
 const verdict=confidence<45?'INSUFFICIENT_EVIDENCE':score>=72?'BUILD':score>=52?'PIVOT':'PAUSE'
 const weakest=[...dimensions].sort((a,b)=>a.score-b.score)[0],strongest=[...dimensions].sort((a,b)=>b.score-a.score)[0]
 const improvements:Improvement[]=[{problem:`${weakest.name} is the biggest current constraint.`,change:`Concentrate the offer around the strongest defensible signal in ${strongest.name.toLowerCase()} and directly test ${weakest.name.toLowerCase()}.`,whyItCouldHelp:'This converts the weakest assumption into an observable test instead of relying on optimism or generic market statistics.',evidence:evidence.filter(e=>e.category.toLowerCase()===weakest.name.toLowerCase()).slice(0,5),expectedImpact:[{dimension:weakest.name,from:weakest.score,to:clamp(weakest.score+15),reason:'Scenario only: stronger evidence could improve the score.'}],validationTest:`Test the revised offer with 10–20 ${customer||'target customers'} and record an observable action such as a purchase, paid commitment, signup, booking or qualified request.`}]
 const stats={sources:evidence.length,independentSources:independent,freshSources:fresh,supporting:evidence.filter(e=>e.polarity==='positive').length,contradicting:evidence.filter(e=>e.polarity==='negative').length,neutral:evidence.filter(e=>e.polarity==='neutral').length,redditSignals:evidence.filter(e=>e.sourceType==='REDDIT').length,freelanceSignals:evidence.filter(e=>e.sourceType==='FREELANCE MARKET').length,newsSignals:evidence.filter(e=>e.sourceType==='NEWS').length,expertSignals:evidence.filter(e=>e.sourceType==='EXPERT ANALYSIS').length,bookSignals:evidence.filter(e=>e.sourceType==='BOOK FRAMEWORK').length}
 return {verdict,score,confidence,evidenceStatus:`${evidence.length} traceable items from ${independent} unique URLs; ${fresh} are fresh/recent.`,summary:verdict==='PAUSE'?'Do not abandon the idea. Strengthen the weakest assumption and retest with real behavior.':verdict==='PIVOT'?`The opportunity has signals, but ${weakest.name.toLowerCase()} needs a stronger angle before major investment.`:verdict==='BUILD'?'Evidence supports a focused build with continued validation.':'There is not enough independent evidence to make a responsible market decision yet.',dimensions,strengths:dimensions.flatMap(d=>d.strengths).slice(0,8),weaknesses:dimensions.flatMap(d=>d.weaknesses).slice(0,8),improvements,evidence,competitors:makeCompetitors(evidence),nextSteps:[`Validate ${weakest.name.toLowerCase()} with measurable customer behavior.`,`Review current news, expert outlook and community demand before each major decision.`,`Run a concrete willingness-to-pay or commitment test.`,`Retest after the proposed change and compare evidence, score and confidence.`],researchStats:stats,methodology:'Market evidence is separated from expert/news context and book frameworks. Reddit and freelance-marketplace results are treated as intent signals, not proof of total-market demand. Every external claim requires a traceable URL; projections are hypotheses, not facts.'}
}
export function demoValidation():Result{return scoreEvidence([{category:'demand',claim:'Live market evidence is not yet verified.',polarity:'neutral',strength:30,sourceType:'baseline'},{category:'problem',claim:'Customer pain is not yet independently verified.',polarity:'neutral',strength:30,sourceType:'baseline'},{category:'competition',claim:'Competitive landscape is not yet mapped.',polarity:'neutral',strength:45,sourceType:'baseline'},{category:'monetization',claim:'Willingness to pay is not yet tested.',polarity:'neutral',strength:30,sourceType:'baseline'},{category:'acquisition',claim:'Acquisition path is not yet verified.',polarity:'neutral',strength:30,sourceType:'baseline'},{category:'risk',claim:'Structural risks are not yet researched.',polarity:'neutral',strength:40,sourceType:'baseline'}])}
