export type Verdict = 'BUILD' | 'PIVOT' | 'PAUSE' | 'INSUFFICIENT_EVIDENCE'
export type Polarity = 'positive' | 'negative' | 'neutral' | 'mixed'
export type Evidence = { category:string; claim:string; sourceUrl?:string; sourceName?:string; sourceType?:string; polarity:Polarity; strength:number; excerpt?:string; publishedAt?:string; retrievedAt?:string; freshness?:'fresh'|'recent'|'stale'|'unknown'; relevance?:number; supports?:string; }
export type Dimension = { name:string; score:number; rationale:string; strengths:string[]; weaknesses:string[]; improvements:string[] }
export type Improvement = { problem:string; change:string; whyItCouldHelp:string; evidence:Evidence[]; expectedImpact:{dimension:string;from:number;to:number;reason:string}[]; validationTest:string }
export type Competitor = { name:string; url:string; description:string; evidence:Evidence[]; threat:'high'|'medium'|'low' }
export type Result = { verdict:Verdict; score:number; confidence:number; evidenceStatus:string; summary:string; dimensions:Dimension[]; strengths:string[]; weaknesses:string[]; improvements:Improvement[]; evidence:Evidence[]; competitors:Competitor[]; nextSteps:string[]; researchStats:{sources:number; independentSources:number; freshSources:number; supporting:number; contradicting:number; neutral:number}; methodology:string }
const clamp=(n:number)=>Math.max(0,Math.min(100,Math.round(n)))
const now=()=>new Date().toISOString()
const freshness=(date?:string):Evidence['freshness']=>{if(!date)return'unknown';const age=(Date.now()-new Date(date).getTime())/86400000;return age<=30?'fresh':age<=180?'recent':age<=730?'stale':'stale'}
function categoryScore(items:Evidence[],category:string,base=45){const xs=items.filter(e=>e.category===category);if(!xs.length)return base;const weighted=xs.reduce((s,e)=>s+e.strength*(e.polarity==='positive'?1:e.polarity==='negative'?-1:0),0);return clamp(base+weighted/Math.max(1,xs.length)*0.72)}
export function scoreEvidence(evidence:Evidence[],idea='',customer=''):Result{
 const demand=categoryScore(evidence,'demand',45), problem=categoryScore(evidence,'problem',45), competition=categoryScore(evidence,'competition',45), monetization=categoryScore(evidence,'monetization',45), acquisition=categoryScore(evidence,'acquisition',45), risk=categoryScore(evidence,'risk',65)
 const dimensions:Dimension[]=[
  {name:'Demand',score:demand,rationale:demand>=65?'Multiple demand signals support the opportunity.':'Demand is not yet strongly demonstrated by the available evidence.',strengths:demand>=65?['Demand signals are visible in the evidence set.']:[],weaknesses:demand<65?['Demand evidence is too weak or mixed.']:[],improvements:['Test the highest-intent customer segment with a concrete offer.']},
  {name:'Problem',score:problem,rationale:problem>=65?'Evidence suggests a meaningful customer problem.':'The problem still needs stronger proof of frequency and severity.',strengths:problem>=65?['Observed pain signals support the problem.']:[],weaknesses:problem<65?['Pain severity is not sufficiently established.']:[],improvements:['Collect direct customer evidence and quantify frequency, cost and urgency.']},
  {name:'Competition',score:competition,rationale:competition>=65?'The landscape leaves room for differentiation.':'Competition or substitutes may make differentiation difficult.',strengths:competition>=65?['A defensible differentiation opportunity may exist.']:[],weaknesses:competition<65?['Existing alternatives may be strong.']:[],improvements:['Choose one underserved segment and define a measurable wedge.']},
  {name:'Monetization',score:monetization,rationale:monetization>=65?'Credible monetization signals are present.':'Willingness to pay is not sufficiently demonstrated.',strengths:monetization>=65?['Comparable pricing or payment signals exist.']:[],weaknesses:monetization<65?['Pricing or willingness-to-pay remains uncertain.']:[],improvements:['Run a pricing or commitment test before building deeply.']},
  {name:'Acquisition',score:acquisition,rationale:acquisition>=65?'A plausible route to customers is visible.':'Customer acquisition remains an important uncertainty.',strengths:acquisition>=65?['A reachable customer channel is visible.']:[],weaknesses:acquisition<65?['The first-customer path is unclear or expensive.']:[],improvements:['Design a first-100-customer channel around the highest-intent audience.']},
  {name:'Risk',score:risk,rationale:risk>=65?'No dominant structural risk is visible in the current evidence.':'Material risks need mitigation before significant investment.',strengths:risk>=65?['No dominant structural risk signal found.']:[],weaknesses:risk<65?['Material risk signals need mitigation.']:[],improvements:['Turn the highest-impact risk into a validation experiment.']}
 ]
 const score=clamp(dimensions.reduce((s,d)=>s+d.score,0)/dimensions.length)
 const independent=new Set(evidence.map(e=>e.sourceUrl||e.sourceName||e.sourceType).filter(Boolean)).size
 const fresh=evidence.filter(e=>e.freshness==='fresh'||e.freshness==='recent').length
 const confidence=clamp(20+Math.min(50,independent*5)+Math.min(20,evidence.length*2)+Math.min(10,fresh*2))
 const verdict:Verdict=confidence<45?'INSUFFICIENT_EVIDENCE':score>=72?'BUILD':score>=52?'PIVOT':'PAUSE'
 const weakest=[...dimensions].sort((a,b)=>a.score-b.score)[0], strongest=[...dimensions].sort((a,b)=>b.score-a.score)[0]
 const improvements:Improvement[]=[{problem:`${weakest.name} is currently the biggest constraint.`,change:`Focus the offer on the strongest defensible signal in ${strongest.name.toLowerCase()} while directly testing ${weakest.name.toLowerCase()}.`,whyItCouldHelp:'A focused change concentrates resources on evidence that already exists and turns the weakest assumption into a measurable experiment.',evidence:evidence.filter(e=>e.category.toLowerCase()===weakest.name.toLowerCase()).slice(0,5),expectedImpact:[{dimension:weakest.name,from:weakest.score,to:clamp(weakest.score+15),reason:'A targeted validation experiment could strengthen the signal; this is a scenario, not a guarantee.'}],validationTest:`Test the revised offer with 10–20 ${customer||'target'} and record a concrete commitment, purchase, signup, or other observable behavior.`}]
 const strengths=dimensions.flatMap(d=>d.strengths).slice(0,8), weaknesses=dimensions.flatMap(d=>d.weaknesses).slice(0,8)
 return {verdict,score,confidence,evidenceStatus:evidence.length?`${evidence.length} evidence items from ${independent} independent sources. Every source is traceable.`:'No live market evidence was retrieved.',summary:verdict==='PAUSE'?'Do not abandon the dream. Fix the weakest assumptions, then retest with evidence.':verdict==='PIVOT'?`The opportunity has signals, but ${weakest.name.toLowerCase()} needs a stronger angle before major investment.`:verdict==='BUILD'?'Evidence supports a focused build with continued validation.':'There is not enough independent evidence to make a responsible decision yet.',dimensions,strengths,weaknesses,improvements,evidence,competitors:[],nextSteps:[`Validate ${weakest.name.toLowerCase()} with a measurable experiment.`,`Run a concrete willingness-to-pay or commitment test.`,`Retest after the proposed change and compare evidence, score and confidence.`],researchStats:{sources:evidence.length,independentSources:independent,freshSources:fresh,supporting:evidence.filter(e=>e.polarity==='positive').length,contradicting:evidence.filter(e=>e.polarity==='negative').length,neutral:evidence.filter(e=>e.polarity==='neutral').length},methodology:'Scores are evidence-weighted, confidence is separate from opportunity score, and projections are hypotheses. No source is treated as proof merely because an AI model mentions it.'}
}
export function demoValidation():Result{return scoreEvidence([{category:'problem',claim:'Problem evidence is not yet independently verified.',polarity:'neutral',strength:35,sourceType:'baseline'},{category:'demand',claim:'Live demand evidence is not yet verified.',polarity:'neutral',strength:30,sourceType:'baseline'},{category:'competition',claim:'Competitive landscape is not yet mapped.',polarity:'neutral',strength:45,sourceType:'baseline'},{category:'monetization',claim:'Willingness to pay is not yet tested.',polarity:'neutral',strength:30,sourceType:'baseline'},{category:'acquisition',claim:'Acquisition economics are not yet verified.',polarity:'neutral',strength:30,sourceType:'baseline'},{category:'risk',claim:'Structural risks are not yet researched.',polarity:'neutral',strength:40,sourceType:'baseline'}])}
